-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJ1eCMM5QdSSn5yX2KRg1Y/fcimI8ewygUCIZCa0Ok2qgCgYIKoZIzj0DAQehRANCAARNY784ZYBujcsb0YsBGMnPqBEtFiYuXs8oTb/RG7TjyjsddeASgQVHx5u17ZMbKqP/PVop7kvsj1NoGnpiqQe3
-----END PRIVATE KEY-----